name: Terraform + Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'bootstrap/**'
      - 'frontend/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bootstrap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Import existing AWS resources (if they exist)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Checking for existing resources to import..."

          set +e  # prevent pipeline from stopping on errors

          # Import DynamoDB Table
          TABLE_NAME="lambda_db_table"
          EXISTS=$(aws dynamodb describe-table --table-name "$TABLE_NAME" 2>/dev/null || true)
          if [ -n "$EXISTS" ]; then
            terraform import aws_dynamodb_table.lambda_db_table "$TABLE_NAME"
          fi

          # Import Lambda Function
          LAMBDA_NAME="API-app"
          EXISTS=$(aws lambda get-function --function-name "$LAMBDA_NAME" 2>/dev/null || true)
          if [ -n "$EXISTS" ]; then
            terraform import aws_lambda_function.API-app "$LAMBDA_NAME"
          fi

          # Import IAM Role
          ROLE_NAME="lambda_exec_role"
          EXISTS=$(aws iam get-role --role-name "$ROLE_NAME" 2>/dev/null || true)
          if [ -n "$EXISTS" ]; then
            terraform import aws_iam_role.lambda_iam_role "$ROLE_NAME"
          fi

          # Import IAM Policy
          POLICY_NAME="lambda_exec_policy"
          POLICY_ARN=$(aws iam list-policies --scope Local --query "Policies[?PolicyName=='$POLICY_NAME'].Arn" --output text)
          if [ -n "$POLICY_ARN" ]; then
            terraform import aws_iam_policy.lambda_iam_policy "$POLICY_ARN"
          fi

          # Import API Gateway
          API_NAME="login-app-api"
          REST_API_ID=$(aws apigateway get-rest-apis --query "items[?name=='$API_NAME'].id" --output text)
          if [ -n "$REST_API_ID" ]; then
            terraform import aws_api_gateway_rest_api.login_app_api "$REST_API_ID"
          fi

          set -e  # restore default error behavior

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Validate
        run: terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  frontend:
    name: Deploy Frontend to GitHub Pages
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload static site to artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
